name: CI

on:
    push:
        branches:
            - feature/deploy
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Build
              run: |
                  npm install
                  npm run-script build
              env:
                  VITE_APP_ID: ${{ secrets.APP_ID }}
                  VITE_APP_KEY: ${{ secrets.APP_KEY }}
                  VITE_API_URI: ${{ secrets.API_URI }}
                  VITE_FULL_RECIPE_LINK: ${{ secrets.FULL_RECIPE_LINK }}

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.0.0
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
                  FOLDER: dist
