name: CI

on:
    push:
        branches:
            - feature/deploy
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Build
              run: |
                  npm install
                  npm run-script build
              env:
                  APP_ID: ${{ secrets.REACT_APP_AAPP_IDPIKey }}
                  APP_KEY: ${{ secrets.APP_KEY }}
                  API_URI: ${{ secrets.API_URI }}
                  FULL_RECIPE_LINK: ${{ secrets.FULL_RECIPE_LINK }}

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BRANCH: gh-pages
